### PR TITLE
Fix REPL spawning

### LINKED ISSUE #34: bootstrap_node.js: Make reading from stdin configurable
Currently, Node.js is hacked to never read from stdin:
https://github.com/hpicgs/node/blob/734d0d6e561a33acfb9ac3b8b4c869f8fb5aa479/lib/internal/bootstrap_node.js#L200-L210

Add a command line parameter (?) to toggle this behaviour.

### PR DESCRIPTION
**Pull request by cmfcmf**
This is now tested and appears to be working.

Closes #34.

### CODE REVIEW

File: src/node_lib.h [hunk 1]
```diff
@@ -100,12 +101,27 @@ NODE_EXTERN void Initialize(const std::string& program_name = "node_lib",
...
+ * Additionally, Node.js will not process any pending events caused by the
+ * JavaScript execution as long as `ProcessEvents` or `RunEventLoop` is
+ * not called.
+ * @param argc The number of arguments.
+ * @param argv List of arguments for the Node.js engine,
+ * where the first argument needs to be the program name.
+ * The number of arguments must correspond to argc.
+ * @param startup_only Controls whether the Node.js JavaScript code also
+ *                     executes additional startup tasks like reading
+ *                     and executing stdin, starting the REPL and so on.
```
Comment (Johannes-Schneider) [inline src/node_lib.h]: Remove whitespaces here. Documentation should be left aligned.

File: src/node_lib.h [hunk 2]
```diff
@@ -80,12 +80,13 @@ bool eventLoopIsRunning();
  * not called.
  * @param program_name The name for the Node.js application.
  * @param node_args List of arguments for the Node.js engine.
- * @param allow_repl Controls whether the node.js REPL gets spawned when stdin
- * is an interactive terminal.
+ * @param startup_only Controls whether the Node.js JavaScript code also
+ *                     executes additional startup tasks like reading
+ *                     and executing stdin, starting the REPL and so on.
```
Comment (Johannes-Schneider) [inline src/node_lib.h]: Remove whitespaces here. Documentation should be left aligned.

**Review by Johannes-Schneider — CHANGES_REQUESTED** [review]

**Review by Johannes-Schneider — APPROVED** [review]
